### ISSUE TITLE
Data not updating Azure SQL 

### ISSUE THREAD

**Issue by gstephens08** [Azure/fieldengineer#11]
I created my own DB and changed the connection string to use my db. It works on the Web App, but doesn't work for the Mobile App. I change the URI for the Mobile App, but still doesn't work. Seems like the local.db created for Android emulator is the only data source working. I completed all jobs to test the db and nothing is not access able in the Mobile App. 

How do I force a sync?

How do I clear the local.db so it rebuilds it? I could find it searching the hard drive.

**Comment by lindydonna** [comment]
If you uninstall the app, it will clear the local database. You can force a sync by using the Refresh button in the app.

**Comment by gstephens08** [comment]
Donna,

Thanks for your reply. I uninstalled it, but I cannot get a connection to the Azure SQL DB. So I took off Authentication and the app is working fine. I will use this to continue development, but I am not sure why the Azure login is not coming up on my phone when I hit "on" or "Refresh." I have triple check my settings on AAD, and its working partially working the the Web App.
1. On the Web App I get prompted to enter my email address, but it doesn't let me enter my password. I cleared the cache and got out of the portal, just to make sure it wasn't being set somewhere else. Am I missing some code? Also, I can't access any link/page after admin, except details while Authentication is on. Everything works fine when it s off.

I figure I need to do something with the following, but I am not using Salesforce or any CRM.

```
    // PATCH tables/Job/48D68C86-6EA6-4C25-AA33-223FC9A27959
    public async Task<Job> PatchJob(string id, Delta<Job> patch)
    {

        Job job = patch.GetEntity();  // get new value
        //var user = this.User as MobileAppUser;
        //var creds = await user.GetIdentityAsync<AzureActiveDirectoryCredentials>();
        //var token = this.Request.Headers.GetValues("x-zumo-auth").First();
        //SalesforceClient client = new SalesforceClient(false);
        //client.SetUser(user.Id, token);
        //ITraceWriter traceWriter = this.Configuration.Services.GetTraceWriter();
        //traceWriter.Info("Patch: userId: " + user.Id + ", token:" + token);            

        //await client.UpdateCase( "0000" + job.JobNumber, job.Status, job.WorkPerformed);

        return await UpdateAsync(id, patch);
    }
```
1. I have uncommented the following the the client and changed AppService to MobileServie;
   
   ```
   public async Task EnsureLogin()
   {
       LoginInProgress = true;
       while (MobileService.CurrentUser == null)
       {
           //await this.AppService.LoginAsync(
           try
           {
               await this.MobileService.LoginAsync(App.UIContext,
                   MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory.ToString());
           }
           catch (Exception ex)
           {
               Console.WriteLine("failed to authenticate: " + ex.Message);
           }
       }
       LoginInProgress = false;
   }
   ```

What did I miss?

I know you're busy, but if you could point me to the right place, as I have been searching all over Azure docs to figure this out.

Thank you,

Geoff

**Comment by lindydonna** [comment]
Where do you seen the prompt to enter your email address?  The web portal doesn't have any authentication built in, so perhaps you turned it on using the Authentication/Authorization feature?

The commented out code for authentication is incorrect, so I'll have to update it to the latest. Please ignore all the auth code on both the client and server.

The right way to add authentication is documented here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/ and https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#how-to-work-with-authentication.

**Comment by gstephens08** [comment]
Donna,

I struggled through a frustrating process of having to change my entire database schema. Why doesn’t azure allow for int as an Id?

I change all fields to be nvarchar, but are all columns of the Azure SQL db require not to be int to work with Moblie and Web Apps? I kept getting the system.int32 can’t be converted to system.string error.

I have an open ticket with Azure on Active Directory 116042714014141. Should I copy it to GitHub for you?

Thanks,

Geoff

**Comment by lindydonna** [comment]
@gstephensDUIS We plan to allow arbitrary Id types in the future, but for now it is string by default. However, you can change this behavior by either adding another column to your DTO that isn't mapped to the database (see https://gist.github.com/lindydonna/2ca523674d34e8a89549), or by using MappedEntityDomainManager. We have a sample for the [mapped domain manager for Mobile Services](https://github.com/paulbatum/FieldEngineerLite/blob/master/FieldEngineerLite.Service/Helpers/DefaultMappedEntityDomainManager.cs). We still need to update the sample to Mobile Apps, but it is the same except for namespaces.

However, we don't recommend using ints as the primary key if you are using offline sync, since IDs need to be generated by the client. It's technically possible to create a GUID that fits into an int, but it's preferable to use an actual GUID type. If you're using an auto-incrementing int, then you need to create a surrogate key that is either a string or GUID.

Wrt to the AAD issue, you don't need to copy it here, since they will take care of it for you.

**Comment by gstephens08** [comment]
Donna,

OK, I am past that and have a jobs table that is a composite of pieces of other tables only for the mobile device. With the Web App I plan on using a Telerik control to quickly build an admin tools set. 

I am trying to get the records to show up in the mobile device, but the URI is wrong, https://dugisfieldstaff.azurewebsites.net/tables/Job?$skip=500&$top=50&__includeDeleted=true. This returns zero records, and then gives the index error. I used postman to verify that changing the values or eliminating them returns the data. As I am still trying to learn this and time is short, how do I eliminate the skip/top or specify their values?

Thank you,

Geoff

**Comment by lindydonna** [comment]
It sounds like the original problem is resolved, so I'm closing this issue. Please open a new issue if something else isn't working.
