### ISSUE TITLE
the mobile client source still references old mobile services code

### ISSUE THREAD

**Issue by ghost** [Azure/fieldengineer#14]
if you open the source code it still references the old mobile services libraries and code to do the offline sync. Does the new Azure.Mobile client sdk not support online/offline?

example: todoitemmanager.cs // To add offline sync support: add the NuGet package WindowsAzure.MobileServices.SQLiteStore

**Comment by lindydonna** [comment]
No, it references the new ones. See https://github.com/Azure-Samples/app-service-mobile-dotnet-fieldengineer/blob/master/client/FieldEngineerLite.Android/packages.config#L3. 

The new packages are Microsoft.Azure.Mobile.Client and the old one is WindowsAzure.MobileServices. The namespaces are the same though, because we didn't want people to have to touch all of their client code when upgrading.

**Comment by ghost** [comment]
something still doesn't tie up.

your field engineer package path looks correct
\packages\Microsoft.Azure.Mobile.Client.2.0.0\lib\monoandroid\Microsoft.WindowsAzure.Mobile.dll

however the new mobile app template on azure starting package is:
\packages*_WindowsAzure.MobileServices.1.3.1_*\lib\portable-win+net45+wp8+wpa81+monotouch+monoandroid\Microsoft.WindowsAzure.Mobile.dll

this is really confusing as new App Projects should look at : packages\Microsoft.Azure.Mobile.Client.2.0.0\

will be great if all the new azure app services project templates for mobile (Xamarin Forms, Xamarin IOS and Xamarin Android) , comments inside template and azure website can be updated with some more guidance on this.

Appreciate they great work Lindy

**Comment by ghost** [comment]
[ToDoDev_Xamarin_Forms - azure asis from template.zip](https://github.com/Azure-Samples/app-service-mobile-dotnet-fieldengineer/files/302030/ToDoDev_Xamarin_Forms.-.azure.asis.from.template.zip)

attached is exact project from Azure quick start.
[Uploading ToDoDev_Xamarin_Forms - azure asis from template.zip…]()

**Comment by lindydonna** [comment]
I looked at your attached project, and I don't see any references to MobileServices 1.3.1 anywhere. Just do a string find on the project, and the only reference is in the namespaces.

Every project has a reference that looks like this:

```
<Reference Include="Microsoft.WindowsAzure.Mobile">
  <HintPath>..\packages\Microsoft.Azure.Mobile.Client.2.0.1\lib\portable-win+net45+wp8+wpa81+monotouch+monoandroid\Microsoft.WindowsAzure.Mobile.dll</HintPath>
</Reference>
```

The assembly name is the same, which is perhaps a little confusing, but the version is correct. If it were the wrong version, it wouldn't even work--you can't use a Mobile Services client library with a Mobile Apps service. See https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-client-and-server-versioning/

**Comment by ghost** [comment]
Maybe nuget gets confused by dll name being the same. Run the project, allow nuget to refresh the packages .

I'll try again with clean project, run, nuget refresh to check outcome.

Thanks anyway Donna, sorry if I wasted your time checking but something is pulling in the old dll  into the azure template project when I run it.

Sent from my iPhone

On 8 Jun 2016, at 5:55 AM, Donna Malayeri <notifications@github.com<mailto:notifications@github.com>> wrote:

I looked at your attached project, and I don't see any references to MobileServices 1.3.1 anywhere. Just do a string find on the project, and the only reference is in the namespaces.

Every project has a reference that looks like this:

<Reference Include="Microsoft.WindowsAzure.Mobile">
  <HintPath>..\packages\Microsoft.Azure.Mobile.Client.2.0.1\lib\portable-win+net45+wp8+wpa81+monotouch+monoandroid\Microsoft.WindowsAzure.Mobile.dll</HintPath>
</Reference>

The assembly name is the same, which is perhaps a little confusing, but the version is correct. If it were the wrong version, it wouldn't even work--you can't use a Mobile Services client library with a Mobile Apps service. See https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-client-and-server-versioning/

##

**Comment by lindydonna** [comment]
How do you know it’s the old DLL?

**Comment by lindydonna** [comment]
Oh, I think I see the issue. There's a code comment in the Xamarin Forms quickstart that references the old package ID: https://github.com/Azure/azure-mobile-apps-quickstarts/blob/master/client/xamarin.forms/ZUMOAPPNAME/TodoItemManager.cs#L1. I'll fix that. Thanks for reporting.

I've opened a pull request to fix the comment: https://github.com/Azure/azure-mobile-apps-quickstarts/pull/58

**Comment by ghost** [comment]
Perfect, thanks Donna.

Have a great day and looking forward to your next video related to azure + mobile

Sent from my iPhone

On 8 Jun 2016, at 8:08 AM, Donna Malayeri <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh, I think I see the issue. There's a code comment in the Xamarin Forms quickstart that references the old package ID: https://github.com/Azure/azure-mobile-apps-quickstarts/blob/master/client/xamarin.forms/ZUMOAPPNAME/TodoItemManager.cs#L1. I'll fix that. Thanks for reporting.

##

**Comment by ghost** [comment]
After nuget refresh or first build click in the assemblies properties in visual studio, it shows as linking to old assembly but only after nuget sync.

It is like nuget cannot tell the difference between the old and new assembly due to the same name being used or something along those lines

Sent from my iPhone

On 8 Jun 2016, at 8:05 AM, Donna Malayeri <notifications@github.com<mailto:notifications@github.com>> wrote:

How do you know it's the old DLL?

**Comment by lindydonna** [comment]
Are you saying that it shows the old path in the project properties window?  Do you see the old NuGet package in your /packages folder?  It's possible (though unlikley) that you need to clean your packages folder if you had the previous NuGet. If you have the wrong project reference, it will be in your csproj file, but the one you attached was correct.

As I mentioned before, both assemblies have the same name, but different NuGet package names and versions. An easy way to figure out which version you're using is to look at the constructor of MobileServiceClient. The new version doesn't have an overload that takes an app key.
